name: 'Terraform'

on:
  push:
    branches:
      - master
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0
        continue-on-error: false

      - name: "HashiCorp - Setup Terraform"
        uses: hashicorp/setup-terraform@v1.2.1
        continue-on-error: false
        with:
          terraform_version: 0.13.6

      - name: "Terraform Format"
        id: fmt
        run: terraform fmt -check -diff
        continue-on-error: false

      - name: "Terraform Lint"
        uses: terraform-linters/setup-tflint@v1.0.7
        continue-on-error: false

      - name: "Setup - Security Scan"
        uses: triat/terraform-security-scan@v2.2.1

      - name: "Terraform init"
        id: init
        run: terraform init -input=false

      - name: "Terraform plan"
        id: plan
        run: terraform plan -input=false -no-color
