name: 'Terraform'

on:
  push:
    branches:
      - master
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0
      - name: "HashiCorp - Setup Terraform"
        uses: hashicorp/setup-terraform@v1.2.1
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
      - name: Terraform Lint
        uses: terraform-linters/setup-tflint@v1.0.7
